### ISSUE TITLE
Memory issues with large datasets

### ISSUE THREAD

**Issue by JennyLouise** [ocean-perception/oplab_pipeline#32]
Memory issues mean correct_images can't be applied to large datasets.

I'm currently trying out splitting the standard error calculations into chunks to reduce memory usage, but I don't think the issue is solely caused by this bit of the code, so it will take a little more work.

**Comment by mattgrove86** [comment]
Hi Jenny,

I work for Sonardyne and have been working with your group on the Bio-cam project. I have written a C++ implementation of your colour correction code which was optimised for processing speed and minimal memory usage. One of the changes I made was to avoid loading all images into memory by first selecting a subset of the input images to process (filtered by altitude) and then only storing a randomly distributed sample of points for each pixel. I used a reservoir sampling method to hold a small buffer of sample pixel values which were then used for downstream processing rather than using the full data-set. In addition to reducing the memory requirement this also has the added advantage of removing ghosting artifacts when using small data-sets.

Thought that might be useful info and if you want anymore details then send me an email (matthew.grove sonardyne.com) and I'd be happy to share my implementation.

Matt

**Comment by miquelmassot** [comment]
From version 0.1.5 the memory issues have been corrected. 
The mean and std values are computed using Welford's online algorithm and wrapped with Numba for speed. Have a look at https://github.com/ocean-perception/oplab_pipeline/blob/master/correct_images/tools/numerical.py#L49
